
# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# focuser.py - Alpaca API responders for Focuser
#
# Author:   Your R. Name <your@email.org> (abc)
#
# -----------------------------------------------------------------------------
# Edit History:
#   Generated by Python Interface Generator for AlpycaDevice
#
# ??-???-????   abc Initial edit

from adafruit_httpserver import Request, Response, JSONResponse, Server, Route, GET, PUT, BAD_REQUEST_400, InvalidPathError
from adafruit_logging import Logger
from shr import PropertyResponse, MethodResponse, PreProcessRequest, \
                StateValue, get_request_field, to_bool
from exceptions import *        # Nothing but exception classes

logger: Logger = None

# ----------------------
# MULTI-INSTANCE SUPPORT
# ----------------------
# If this is > 0 then it means that multiple devices of this type are supported.
# Each responder on_get() and on_put() is called with a devnum parameter to indicate
# which instance of the device (0-based) is being called by the client. Leave this
# set to 0 for the simple case of controlling only one instance of this device type.
#
maxdev = 0                      # Single instance

# -----------
# DEVICE INFO
# -----------
# Static metadata not subject to configuration changes
## EDIT FOR YOUR DEVICE ##
class FocuserMetadata:
    """ Metadata describing the Focuser Device. Edit for your device"""
    Name = 'Sample Focuser'
    Version = '##DRIVER VERSION AS STRING##'
    Description = 'My ASCOM Focuser'
    DeviceType = 'Focuser'
    DeviceID = '##GENERATE A NEW GUID AND PASTE HERE##' # https://guidgenerator.com/online-guid-generator.aspx
    Info = 'Alpaca Sample Device\nImplements IFocuser\nASCOM Initiative'
    MaxDeviceNumber = maxdev
    InterfaceVersion = ##YOUR DEVICE INTERFACE VERSION##        # IFocuserVxxx


# --------------------
# RESOURCE CONTROLLERS
# --------------------

class action:
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(MethodResponse(req, NotImplementedException()).dict)

class commandblind:
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(MethodResponse(req, NotImplementedException()).dict)

class commandbool:
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(MethodResponse(req, NotImplementedException()).dict)

class commandstring:
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(MethodResponse(req, NotImplementedException()).dict)

class connect:
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            # ------------------------
            ### CONNECT THE DEVICE ###
            # ------------------------
            return JSONResponse(MethodResponse(req).dict)
        except Exception as ex:
            return JSONResponse(MethodResponse(req,
                            DriverException(0x500, 'Focuser.Connect failed', ex)).dict)

class connected:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            # -------------------------------------
            is_conn = ### READ CONN STATE ###
            # -------------------------------------
            return JSONResponse(PropertyResponse(is_conn, req).dict)
        except Exception as ex:
            return JSONResponse(MethodResponse(req, DriverException(0x500, 'Focuser.Connected failed', ex)).dict)
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        conn_str = get_request_field('Connected', req)
        conn = to_bool(conn_str)              # Raises 400 Bad Request if str to bool fails

        try:
            # --------------------------------------
            ### CONNECT OR DISCONNECT THE DEVICE ###
            # --------------------------------------
            return JSONResponse(MethodResponse(req).dict)
        except Exception as ex:
            return JSONResponse(MethodResponse(req, # Put is actually like a method :-(
                            DriverException(0x500, 'Focuser.Connected failed', ex)).dict)

class connecting:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            # ------------------------------
            val = ## GET CONNECTING STATE ##
            # ------------------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Connecting failed', ex)).dict)

class description:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(PropertyResponse(FocuserMetadata.Description, req).dict)

class devicestate:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        try:
            # ----------------------
            val = []
            # val.append(StateValue('## NAME ##', ## GET VAL ##))
            # Repeat for each of the operational states per the device spec
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'focuser.Devicestate failed', ex)).dict)


class disconnect:
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            # ---------------------------
            ### DISCONNECT THE DEVICE ###
            # ---------------------------
            return JSONResponse(MethodResponse(req).dict)
        except Exception as ex:
            return JSONResponse(MethodResponse(req,
                            DriverException(0x500, 'Focuser.Disconnect failed', ex)).dict)

class driverinfo:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(PropertyResponse(FocuserMetadata.Info, req).dict)

class interfaceversion:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(PropertyResponse(FocuserMetadata.InterfaceVersion, req).dict)

class driverversion():
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(PropertyResponse(FocuserMetadata.Version, req).dict)

class name():
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(PropertyResponse(FocuserMetadata.Name, req).dict)

class supportedactions:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        return JSONResponse(PropertyResponse([], req).dict)  # Not PropertyNotImplemented

class absolute:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Absolute failed', ex)).dict)

class ismoving:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Ismoving failed', ex)).dict)

class maxincrement:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Maxincrement failed', ex)).dict)

class maxstep:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Maxstep failed', ex)).dict)

class position:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Position failed', ex)).dict)

class stepsize:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Stepsize failed', ex)).dict)

class tempcomp:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Tempcomp failed', ex)).dict)
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not ## IS DEV CONNECTED ##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        tempcompstr = get_request_field('TempComp', req)      # Raises 400 bad request if missing
        try:
            tempcomp = to_bool(tempcompstr)
        except:
            return JSONResponse(MethodResponse(req,
                            InvalidValueException(f'TempComp {tempcompstr} not a valid boolean.')).dict)

        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            return JSONResponse(MethodResponse(req).dict)
        except Exception as ex:
            return JSONResponse(MethodResponse(req,
                            DriverException(0x500, 'Focuser.Tempcomp failed', ex)).dict)

class tempcompavailable:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Tempcompavailable failed', ex)).dict)

class temperature:
    @PreProcessRequest(maxdev)
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not ##IS DEV CONNECTED##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # ----------------------
            val = ## GET PROPERTY ##
            # ----------------------
            return JSONResponse(PropertyResponse(val, req).dict)
        except Exception as ex:
            return JSONResponse(PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Temperature failed', ex)).dict)

class halt:
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not ## IS DEV CONNECTED ##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            return JSONResponse(MethodResponse(req).dict)
        except Exception as ex:
            return JSONResponse(MethodResponse(req,
                            DriverException(0x500, 'Focuser.Halt failed', ex)).dict)

class move:
    @PreProcessRequest(maxdev)
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not ## IS DEV CONNECTED ##:
            return JSONResponse(PropertyResponse(None, req,
                            NotConnectedException()).dict)
        
        positionstr = get_request_field('Position', req)      # Raises 400 bad request if missing
        try:
            position = int(positionstr)
        except:
            return JSONResponse(MethodResponse(req,
                            InvalidValueException(f'Position {positionstr} not a valid integer.')).dict)
        ### RANGE CHECK AS NEEDED ###  # Raise Alpaca InvalidValueException with details!
        try:
            # -----------------------------
            ### DEVICE OPERATION(PARAM) ###
            # -----------------------------
            return JSONResponse(MethodResponse(req).dict)
        except Exception as ex:
            return JSONResponse(MethodResponse(req,
                            DriverException(0x500, 'Focuser.Move failed', ex)).dict)

def init_routes(server: Server, api_version):
    server.add_routes([
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/action', PUT, action.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/commandblind', PUT, commandblind.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/commandbool', PUT, commandbool.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/commandstring', PUT, commandstring.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/connect', PUT, connect.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/connected', GET, connected.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/connected', PUT, connected.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/connecting', GET, connecting.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/description', GET, description.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/devicestate', GET, devicestate.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/disconnect', PUT, disconnect.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/driverinfo', GET, driverinfo.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/interfaceversion', GET, interfaceversion.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/driverversion', GET, driverversion.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/name', GET, name.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/supportedactions', GET, supportedactions.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/absolute', GET, absolute.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/ismoving', GET, ismoving.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/maxincrement', GET, maxincrement.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/maxstep', GET, maxstep.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/position', GET, position.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/stepsize', GET, stepsize.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/tempcomp', GET, tempcomp.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/tempcomp', PUT, tempcomp.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/tempcompavailable', GET, tempcompavailable.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/temperature', GET, temperature.on_get),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/halt', PUT, halt.on_put),
        Route(f'/api/v{api_version}/covercalibrator/<devnum>/move', PUT, move.on_put),
    ])
